
package League_Package;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


public class BoroaLeague extends javax.swing.JFrame {

    public BoroaLeague() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        setimageLabel(LB_logoleague, "src/imagen/LogoBoroa.jpg");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DG_CraerEquipo = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LB_FifaLogo = new javax.swing.JLabel();
        TF_addEstadio = new javax.swing.JTextField();
        TF_addPais = new javax.swing.JTextField();
        TF_addNombreEquipo = new javax.swing.JTextField();
        TF_addCiudad = new javax.swing.JTextField();
        PN_SalirCE = new javax.swing.JPanel();
        LB_salir1 = new javax.swing.JLabel();
        PN_AgregarEquipo = new javax.swing.JPanel();
        LB_AgegarEquipo = new javax.swing.JLabel();
        DG_CraerJuagdor = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LB_FifaLogo1 = new javax.swing.JLabel();
        TF_addEstadio1 = new javax.swing.JTextField();
        TF_addPais1 = new javax.swing.JTextField();
        TF_addNombreEquipo1 = new javax.swing.JTextField();
        TF_addCiudad1 = new javax.swing.JTextField();
        PN_SalirCE1 = new javax.swing.JPanel();
        LB_salir2 = new javax.swing.JLabel();
        PN_AgregarEquipo1 = new javax.swing.JPanel();
        LB_AgegarEquipo1 = new javax.swing.JLabel();
        DG_Transferir = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        TB_AdminMenu = new javax.swing.JToolBar();
        LB_CrearEquipo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        LB_CraerJugador = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        LB_Transferir = new javax.swing.JLabel();
        LB_logoleague = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PN_Salir = new javax.swing.JPanel();
        LB_salir = new javax.swing.JLabel();
        MB_menu = new javax.swing.JMenuBar();
        M_Opciones = new javax.swing.JMenu();
        MI_CrearEquipo = new javax.swing.JMenuItem();
        MI_CraerJugador = new javax.swing.JMenuItem();
        MI_Transferir = new javax.swing.JMenuItem();
        M_Ayuda = new javax.swing.JMenu();

        DG_CraerEquipo.setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 204, 255));
        jLabel1.setText("estadio");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 130, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 204, 255));
        jLabel2.setText("Pais del equipo");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 130, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 204, 255));
        jLabel3.setText("Nombre del equipo");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 130, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 204, 255));
        jLabel4.setText("ciudad ");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 130, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Crear Equipos");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 240, 70));
        jPanel4.add(LB_FifaLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 50, 30));
        jPanel4.add(TF_addEstadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 210, -1));
        jPanel4.add(TF_addPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 210, -1));
        jPanel4.add(TF_addNombreEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 210, -1));
        jPanel4.add(TF_addCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 210, -1));

        PN_SalirCE.setBackground(new java.awt.Color(153, 153, 153));
        PN_SalirCE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PN_SalirCE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PN_SalirCEMouseClicked(evt);
            }
        });

        LB_salir1.setForeground(new java.awt.Color(0, 0, 0));
        LB_salir1.setText("X");

        javax.swing.GroupLayout PN_SalirCELayout = new javax.swing.GroupLayout(PN_SalirCE);
        PN_SalirCE.setLayout(PN_SalirCELayout);
        PN_SalirCELayout.setHorizontalGroup(
            PN_SalirCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN_SalirCELayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LB_salir1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PN_SalirCELayout.setVerticalGroup(
            PN_SalirCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_SalirCELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_salir1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(PN_SalirCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        PN_AgregarEquipo.setBackground(new java.awt.Color(0, 153, 153));

        LB_AgegarEquipo.setBackground(new java.awt.Color(204, 204, 204));
        LB_AgegarEquipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LB_AgegarEquipo.setText("Agregar");

        javax.swing.GroupLayout PN_AgregarEquipoLayout = new javax.swing.GroupLayout(PN_AgregarEquipo);
        PN_AgregarEquipo.setLayout(PN_AgregarEquipoLayout);
        PN_AgregarEquipoLayout.setHorizontalGroup(
            PN_AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN_AgregarEquipoLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(LB_AgegarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        PN_AgregarEquipoLayout.setVerticalGroup(
            PN_AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_AgregarEquipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_AgegarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(PN_AgregarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 120, 50));

        javax.swing.GroupLayout DG_CraerEquipoLayout = new javax.swing.GroupLayout(DG_CraerEquipo.getContentPane());
        DG_CraerEquipo.getContentPane().setLayout(DG_CraerEquipoLayout);
        DG_CraerEquipoLayout.setHorizontalGroup(
            DG_CraerEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );
        DG_CraerEquipoLayout.setVerticalGroup(
            DG_CraerEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 204, 255));
        jLabel6.setText("estadio");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 130, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 204, 255));
        jLabel7.setText("Pais del equipo");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 130, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 204, 255));
        jLabel8.setText("Nombre del equipo");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 130, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 204, 255));
        jLabel9.setText("ciudad ");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 130, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Crear Jugadores");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 240, 70));
        jPanel5.add(LB_FifaLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 50, 30));
        jPanel5.add(TF_addEstadio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 210, -1));
        jPanel5.add(TF_addPais1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 210, -1));
        jPanel5.add(TF_addNombreEquipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 210, -1));
        jPanel5.add(TF_addCiudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 210, -1));

        PN_SalirCE1.setBackground(new java.awt.Color(153, 153, 153));
        PN_SalirCE1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PN_SalirCE1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PN_SalirCE1MouseClicked(evt);
            }
        });

        LB_salir2.setForeground(new java.awt.Color(0, 0, 0));
        LB_salir2.setText("X");

        javax.swing.GroupLayout PN_SalirCE1Layout = new javax.swing.GroupLayout(PN_SalirCE1);
        PN_SalirCE1.setLayout(PN_SalirCE1Layout);
        PN_SalirCE1Layout.setHorizontalGroup(
            PN_SalirCE1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN_SalirCE1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LB_salir2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PN_SalirCE1Layout.setVerticalGroup(
            PN_SalirCE1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_SalirCE1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_salir2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(PN_SalirCE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        PN_AgregarEquipo1.setBackground(new java.awt.Color(0, 153, 153));

        LB_AgegarEquipo1.setBackground(new java.awt.Color(204, 204, 204));
        LB_AgegarEquipo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LB_AgegarEquipo1.setText("Agregar");

        javax.swing.GroupLayout PN_AgregarEquipo1Layout = new javax.swing.GroupLayout(PN_AgregarEquipo1);
        PN_AgregarEquipo1.setLayout(PN_AgregarEquipo1Layout);
        PN_AgregarEquipo1Layout.setHorizontalGroup(
            PN_AgregarEquipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN_AgregarEquipo1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(LB_AgegarEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        PN_AgregarEquipo1Layout.setVerticalGroup(
            PN_AgregarEquipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_AgregarEquipo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_AgegarEquipo1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(PN_AgregarEquipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 120, 50));

        javax.swing.GroupLayout DG_CraerJuagdorLayout = new javax.swing.GroupLayout(DG_CraerJuagdor.getContentPane());
        DG_CraerJuagdor.getContentPane().setLayout(DG_CraerJuagdorLayout);
        DG_CraerJuagdorLayout.setHorizontalGroup(
            DG_CraerJuagdorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        DG_CraerJuagdorLayout.setVerticalGroup(
            DG_CraerJuagdorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DG_TransferirLayout = new javax.swing.GroupLayout(DG_Transferir.getContentPane());
        DG_Transferir.getContentPane().setLayout(DG_TransferirLayout);
        DG_TransferirLayout.setHorizontalGroup(
            DG_TransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DG_TransferirLayout.setVerticalGroup(
            DG_TransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TB_AdminMenu.setBackground(new java.awt.Color(0, 153, 153));
        TB_AdminMenu.setForeground(new java.awt.Color(153, 255, 204));
        TB_AdminMenu.setRollover(true);

        LB_CrearEquipo.setText("Crear Equipo");
        LB_CrearEquipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LB_CrearEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LB_CrearEquipoMouseClicked(evt);
            }
        });
        TB_AdminMenu.add(LB_CrearEquipo);
        TB_AdminMenu.add(jSeparator1);

        LB_CraerJugador.setText("Crear Jugador");
        LB_CraerJugador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TB_AdminMenu.add(LB_CraerJugador);
        TB_AdminMenu.add(jSeparator2);

        LB_Transferir.setText("Transfeir");
        LB_Transferir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TB_AdminMenu.add(LB_Transferir);

        jPanel1.add(TB_AdminMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 40));
        jPanel1.add(LB_logoleague, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 600, 380));

        jPanel2.setBackground(new java.awt.Color(60, 105, 105));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 700, 60));

        PN_Salir.setBackground(new java.awt.Color(153, 153, 153));
        PN_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PN_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PN_SalirMouseClicked(evt);
            }
        });

        LB_salir.setForeground(new java.awt.Color(0, 0, 0));
        LB_salir.setText("X");

        javax.swing.GroupLayout PN_SalirLayout = new javax.swing.GroupLayout(PN_Salir);
        PN_Salir.setLayout(PN_SalirLayout);
        PN_SalirLayout.setHorizontalGroup(
            PN_SalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN_SalirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LB_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PN_SalirLayout.setVerticalGroup(
            PN_SalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_SalirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(PN_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 20, 30));

        MB_menu.setBackground(new java.awt.Color(204, 204, 204));

        M_Opciones.setText("Opciones");

        MI_CrearEquipo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MI_CrearEquipo.setText("Crear Equipo");
        M_Opciones.add(MI_CrearEquipo);

        MI_CraerJugador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MI_CraerJugador.setText("Craer Jugador");
        M_Opciones.add(MI_CraerJugador);

        MI_Transferir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MI_Transferir.setText("Transferir");
        M_Opciones.add(MI_Transferir);

        MB_menu.add(M_Opciones);

        M_Ayuda.setText("Ayuda");
        MB_menu.add(M_Ayuda);

        setJMenuBar(MB_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PN_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PN_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_PN_SalirMouseClicked

    private void LB_CrearEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LB_CrearEquipoMouseClicked
        this.setVisible(false);
        AbrirMenuCrearEquipo(true);
    }//GEN-LAST:event_LB_CrearEquipoMouseClicked

    private void PN_SalirCEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PN_SalirCEMouseClicked
        DG_CraerEquipo.setVisible(false);
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }//GEN-LAST:event_PN_SalirCEMouseClicked

    private void PN_SalirCE1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PN_SalirCE1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PN_SalirCE1MouseClicked

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoroaLeague.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoroaLeague.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoroaLeague.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoroaLeague.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoroaLeague().setVisible(true);
            }
        });
    }
    
    public void setimageLabel(JLabel nomLabel, String ruta) {
        ImageIcon imagen = new ImageIcon(ruta);
        Icon icon = new ImageIcon(
                imagen.getImage().getScaledInstance(nomLabel.getWidth(), nomLabel.getHeight(), Image.SCALE_DEFAULT));
        nomLabel.setIcon(icon);
        this.repaint();
    }
    
    public void AbrirMenuCrearEquipo(boolean vista){
        DG_CraerEquipo.pack();
        DG_CraerEquipo.setLocationRelativeTo(this);
        setimageLabel(LB_FifaLogo, "src/imagen/LogoFifa.png");
        DG_CraerEquipo.setModal(vista);
        DG_CraerEquipo.setVisible(vista);
    }
    
    public void crearEquipo(){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DG_CraerEquipo;
    private javax.swing.JDialog DG_CraerJuagdor;
    private javax.swing.JDialog DG_Transferir;
    private javax.swing.JLabel LB_AgegarEquipo;
    private javax.swing.JLabel LB_AgegarEquipo1;
    private javax.swing.JLabel LB_CraerJugador;
    private javax.swing.JLabel LB_CrearEquipo;
    private javax.swing.JLabel LB_FifaLogo;
    private javax.swing.JLabel LB_FifaLogo1;
    private javax.swing.JLabel LB_Transferir;
    private javax.swing.JLabel LB_logoleague;
    private javax.swing.JLabel LB_salir;
    private javax.swing.JLabel LB_salir1;
    private javax.swing.JLabel LB_salir2;
    private javax.swing.JMenuBar MB_menu;
    private javax.swing.JMenuItem MI_CraerJugador;
    private javax.swing.JMenuItem MI_CrearEquipo;
    private javax.swing.JMenuItem MI_Transferir;
    private javax.swing.JMenu M_Ayuda;
    private javax.swing.JMenu M_Opciones;
    private javax.swing.JPanel PN_AgregarEquipo;
    private javax.swing.JPanel PN_AgregarEquipo1;
    private javax.swing.JPanel PN_Salir;
    private javax.swing.JPanel PN_SalirCE;
    private javax.swing.JPanel PN_SalirCE1;
    private javax.swing.JToolBar TB_AdminMenu;
    private javax.swing.JTextField TF_addCiudad;
    private javax.swing.JTextField TF_addCiudad1;
    private javax.swing.JTextField TF_addEstadio;
    private javax.swing.JTextField TF_addEstadio1;
    private javax.swing.JTextField TF_addNombreEquipo;
    private javax.swing.JTextField TF_addNombreEquipo1;
    private javax.swing.JTextField TF_addPais;
    private javax.swing.JTextField TF_addPais1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
